### ISSUE TITLE
How to do UserCache in practice?

### ISSUE THREAD

**Issue by zippoxer** [benbjohnson/wtf#11]
Hi Ben (or anyone who wanna help),

After you answered my last question, I kept transactions internally within the database implementation and finally I stumbled upon a use case where not exposing transactions is the right decision ;-)

I want to raise another topic for discussion as well. Should be a trivial one.
In your [medium post](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1#.h10mujcvz), you were instantiating the services in the main package. This way, it's easy to inject wrapper services like `UserCache` application-wise.

However, the WTF application introduces a `Client` interface which instantiates the services instead. With this approach, I can't tell where to inject wrapper services (say `DialCache`) so they will be used by default across our application.

Of course, we can inject `DialCache` directly to `http.DialHandler.DialService`, but this would require us to manually inject our wrapper services again in every package we use `Client`.

I thought about having a wrapper to our database `Client` (maybe `CachedClient`) with which we'll implement caching wrapper for the services we want and return those instead (i.e. `CachedClient.DialService()` returns our `DialCache` implementation).

What do you think?

Thanks for reading so far ;-)

**Comment by jpudney** [comment]
Hi @zippoxer, I've been playing around with an [example app](https://github.com/jpudney/beerapp) to try and flesh out the ideas that Ben, et al. have proposed. Here I've made the cache implement the same interface as the db and then wrap the db with it before adding it into the handler.

While not a silver bullet (still trying to investigate this further myself) it should be a good start.

**Comment by benbjohnson** [comment]
The `Client` is really just meant to be an easy way to instantiate services from a common configuration (e.g. a `*sql.DB` or `URL`). It's not a necessary piece and I actually may remove it to avoid confusion.

In your `main` package, you can wire up the dependencies like:

```go
func main() {
	// Connect to DB.
	db, err := sql.Open(...)
	if err != nil {
		log.Fatal(err)
	}

	// Create cached service.
	service := myapp.NewDialCache(postgres.NewDialService(db))

	// Attach to HTTP handler.
	server := http.NewServer()
	server.DialHandler.DialService = service

	// Run HTTP server.
	if errserver.Open(); err != nil {
		log.Fatal(err)
	}
}
```

You could do a `CacheClient` but I find that different `main` packages have different requirements about how dependencies are layered.

For example, your HTTP server app may have services wrapped like:

```
http.DialHandler -> wtf.DialCache -> bolt.DialService
```

Whereas your client application probably needs something like:

```
http.DialService
```

Or, it may have a cache on the client side but with different settings. If you have a single server process serving from a database then you may not want to expire items in the cache. However, on the client you don't know if items have been updated so you may want a TTL.

While it's more code to wire up the list of different dependencies for each binary you're making, I find that it usually makes the most sense to be specific and not share configuration.

Does that answer your question?

**Comment by zippoxer** [comment]
@benbjohnson 
Yes, that answers my question. Thank you very much ;-)

@jpudney 
Looks great, thanks :)
