### ISSUE TITLE
Is there a good way to add methods for Dial?

### ISSUE THREAD

**Issue by zh-lab** [benbjohnson/wtf#12]
Hi!
Thanks for your awesome package layout design first!

When I try to write some code based on your design I met a question then. So I posted here 😃 

If I want to add some methods for domain types (Dial in wtf), Should I add them directly in root package?

**Comment by benbjohnson** [comment]
@zh-lab Yes, the methods would go in the root package. Methods on `Dial` should only be related to the domain and not to any dependencies though. If you have implementation-specific functions then you can add them as regular functions (with the first argument being the `Dial`) to the appropriate subpackage.
