### ISSUE TITLE
Add comments on the itob function #session.go

### ISSUE THREAD

**Issue by izobiz** [benbjohnson/wtf#3]
A little comment will help. Its not clear at first sight why an int is being changed to a byte

**Comment by benbjohnson** [comment]
@izobiz Good point! I added a comment here: https://github.com/benbjohnson/wtf/blob/01ad64c7ca6e54df4be7166538bfe4d8c43294a4/bolt/session.go#L59-L67

**Comment by izobiz** [comment]
That's nice. and i listened to your interview on Go-Time podcast. awesome
