### ISSUE TITLE
Add a comment to dial_service.go line 8

### ISSUE THREAD

**Issue by izobiz** [benbjohnson/wtf#4]
Am confused on what `var _ wtf.DialService = &DialService{}` is doing or is supposed to do

**Comment by benbjohnson** [comment]
Hmm, I thought I added a comment for that. Thanks for catching that. Fixed here:

https://github.com/benbjohnson/wtf/blob/4336d7a1e5283c7482754b3112ae12a829b23cf3/bolt/dial_service.go#L8-L9

That assignment causes the compiler to check that our `*bolt.DialService` implements the  `wtf.DialService` interface.

Also, can you add line comments in the pull request next time? It makes it easier to see the related line.

**Comment by izobiz** [comment]
How do i do this? I quite new to github.
`Also, can you add line comments in the pull request next time? It makes it easier to see the related line`

**Comment by benbjohnson** [comment]
Go to the "Files" tab in the pull request and then click on the line you want to comment on. That'll open a text box where you can add your comment.

https://help.github.com/articles/commenting-on-a-pull-request/
